services:
    clash82.ez_website_switcher.twig_extension:
        class: Clash82\EzPlatformWebsiteSwitcherBundle\Twig\WebsiteSwitcherTwigExtension
        arguments:
            - "@ezpublish.translation_helper"
            - "@ezpublish.locale.converter"
            - cookieName: "%ez_website_switcher.cookie_name%"
              days: "%ez_website_switcher.days%"
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            - { name: twig.extension }
